### PR TITLE
Sucks, chucks, makes thirst less cancer

### PR DESCRIPTION
**Pull request by karmaisblackandbluepilled**
thirsty for cum eh?

### CODE REVIEW

**Comment by Doosteroni** [comment]
waht thae FUCk

**Comment by Doosteroni** [comment]
oh is watweer PR cool baserdf 100% homealses

**Comment by karmaisblackandbluepilled** [comment]
who are you

**Comment by Doosteroni** [comment]
you wuill never knooooooow

**Comment by karmaisblackandbluepilled** [comment]
the hog

**Pull request merged**
