### PR TITLE
Removes prosthetics overheating

### PR DESCRIPTION
**Pull request by karmaisblackandbluepilled**
why was this added

### CODE REVIEW

**Comment by SireTurret2** [comment]
Synths don't feel pain, so this was added as a nerf

**Comment by karmaisblackandbluepilled** [comment]
why don't synths feel pain....

**Comment by Jeff-Dome** [comment]
Because in bay fag-station, they don't have the proc (Does feel pain) or whatever it's called, and therefore they overheat in a spacehole, but due to having no pain at all.. this is hardly a nerf lol!

**Comment by karmaisblackandbluepilled** [comment]
overheating deals damage and slows you down though.

**Comment by Jeff-Dome** [comment]
It can be completely countered by a cooling pack, which could be made in the autolathe from what I last remember, unless that was removed ages ago.

**Comment by PapaSejd** [comment]
Ill leave this up for debate, its not clear if this a good change yet

**Comment by Jeff-Dome** [comment]
Yeah, I think the synths don't have the (can_feel_pain(), which is stupid given how resistant robotic parts can be. the counter to them is burn damage but they can easily vent around that, it's barely a nerf to be fair. A better change would be preventing people from becoming JC Dick cut 2.

**Comment by Jeff-Dome** [comment]
Perhaps, a point system for robotic parts?

**Comment by karmaisblackandbluepilled** [comment]
perhaps removing being a prostheticoid from roundstart. You want to be a robot? Get research to augment you.
also who are you on the discord

**Comment by Jeff-Dome** [comment]
Either or, really. Full remove round start access or points for parts, but it's more about what direction we want the parts of gameplay to go.

**Comment by karmaisblackandbluepilled** [comment]
i'd rather just have it be removed from roundstart. It would also hopefully fit into the nebulous and unwritten lore that I'd like to write in like a week.

**Comment by Jeff-Dome** [comment]
I agree also, given how powerful they can turn out to be, without the counter play that bay coded in for robo-fags, I.E. the stun guns, as stun guns caused extreme damage to cells within synths, IPCs and general robotics, then again the whispering shit of lore is rather retarded.

**Comment by karmaisblackandbluepilled** [comment]
saying f*g makes git delete your acc and this repo. also I don't really care about things being overpowered, I just care about them being "cool" or interesting and especially I care about them not being bullshit like overheating when you put on an EVA suit when someone breaches the walls

**Comment by Jeff-Dome** [comment]
GIthub can suck my left nut sack but to be fair, all robotics shit can go into the das poopenfarden

**Comment by karmaisblackandbluepilled** [comment]
i'd rather just have robotics be only for science, but hard to get
fuck having it built roundstart, get to WORK! Build it you slave! You want it? Earn it!

**Comment by Jeff-Dome** [comment]
The simple adage, that a famous male actor once said. "Fucking slaves, get your ass back here", quite a poet as well, because said, black people should have to work for their robotic parts and not steal them off whitey I.E. stealing them from the dollar store so they can quickly rush out of their cryo pods.

**Comment by Doosteroni** [comment]
I think you are getting side-tracked

**Comment by Jeff-Dome** [comment]
Gameplay design is an equally comment in regardless to the expressed purpose of robotic limbs because it's begging the question of why this is in the first place and how should it work and why should it work.

**Comment by karmaisblackandbluepilled** [comment]
where am i

**Comment by Orange-jpg** [comment]
sneed

\

**Comment by Doosteroni** [comment]
Remove prosthetics. They are stupid and dumb, if you lose a limb you shouldn't be able to go to a doctor and woop de do nothing happened. Atleast make them fucking hook hands like pirates or some shit. Why hasn't this been closed yet?

**Comment by karmaisblackandbluepilled** [comment]
no that's retarded and you're retarded

**Comment by Doosteroni** [comment]
I'm not the tard who opened this PR

**Comment by PapaSejd** [comment]
I'd like to know whether this PR is to be merged, I dont want to hear about prosthetics BS

**Comment by Doosteroni** [comment]
Just close it!

**Comment by karmaisblackandbluepilled** [comment]
merge it by Allah

**Comment by Doosteroni** [comment]
Fucking inbreds

**Comment by Doosteroni** [comment]
Hey travis failed
revert

**Comment by PapaSejd** [comment]
It always fails

**Comment by Doosteroni** [comment]
Then remove it DUHH

**Comment by Jeff-Dome** [comment]
Interstation code never plays nice with Travis. It's natural law. I've never figured out why it doesn't play nice.

**Comment by Orange-jpg** [comment]
sneed

**Pull request merged**
